#!/usr/bin/env python3

"""
Read_Table reads a table from the internet and stores
in a .csv file
"""

__author__     =  "Paul Mendoza"
__copyright__  =  "Copyright 2016, Planet Earth"
__credits__    = ["Sunil Chirayath",
                  "Charles Folden",
                  "Jeremy Conlin"]
__license__    =  "GPL"
__version__    =  "1.0.1"
__maintainer__ =  "Paul Mendoza"
__email__      =  "paul.m.mendoza@gmail.com"
__status__     =  "Production"

################################################################
##################### Import packages ##########################
################################################################

import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime



Elements_W_Atomic_Mass=pd.read_html(
  'physics.nist.gov/cgi-bin/Compositions/stand_alone.pl?ele=&ascii=html&isotype=all'
				   )

print(Elements_W_Atomic_Mass)